name = "TechnoCraft: Baianos"
author = "André Augusto"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "549905fd1eff528f123382e9f38b81b6d9fbb1264675c6345df53533f42907e2"

[versions]
forge = "43.2.6"
minecraft = "1.19.2"
