name = "TechnoCraft: Baianos"
author = "André Augusto"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15c0af9cab4f797becdd8aa5df943e3f61f3e24bb6f5b446f1b4840c4a8a07da"

[versions]
forge = "43.2.6"
minecraft = "1.19.2"
