name = "TechnoCraft: Baianos"
author = "André Augusto"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83e473ee601a17a735b52bc17d0a906760e46315b7edf4672c54865723c187c0"

[versions]
forge = "43.2.6"
minecraft = "1.19.2"
