name = "TechnoCraft: Baianos"
author = "André Augusto"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d93bf90a19d7c3538014460c2a02adf371eec1d3bcfc1bf6785d36eede89794"

[versions]
forge = "43.2.6"
minecraft = "1.19.2"
