name = "TechnoCraft"
author = "André"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf679d246c80a776f53548f9578c2a75c4b2ef3cbb61748b1735c205503351f8"

[versions]
forge = "43.2.1"
minecraft = "1.19.2"
