name = "TechnoCraft: Baianos"
author = "André Augusto"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7adbbf199027ae16dea47c8296c6411f52a914689e1b9c6ad4cabbc6c65aeee"

[versions]
forge = "43.2.6"
minecraft = "1.19.2"
