name = "TechnoCraft: Baianos"
author = "André Augusto"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a013a0f87440a266c3debcb904a895000c714bde1c21a5257d22c4e42656122"

[versions]
forge = "43.2.6"
minecraft = "1.19.2"
